feat: avatar component added
Panenco/panenco-ui pull request #240
Opened 2022-03-30 08:35 UTC by Yhuley

2022-03-30 13:33 UTC, lazzystep commented
Could you please provide more info about it. Ideally link to trello ticket as well. Thanks in advance!

2022-04-01 08:24 UTC, vlacher12 commented
Have a look at https://mui.com/components/avatars/ . Probably, we can find some inspiration there. AvatarGroup also could be implemented

2022-04-18 12:26 UTC, sergdeev approved these changes

2022-04-20 13:13 UTC, taras-venger approved these changes

2022-04-20 14:18 UTC, sergdeev commented on src/components/avatar/index.tsx
> +      <Tooltip content={email || `${firstName || ''} ${lastName || ''}`} {...tooltipProps}>
comment from Sasha
кароч імейл і ім'я це залежить від контексту
коли відоме ім'я то тоді його прокидуватимемоʼ
коли невідоме тоді імейл прокидуватимемо

2022-04-26 17:48 UTC, sergdeev approved these changes

2022-04-29 12:04 UTC, vlacher12 requested changes

2022-04-29 12:04 UTC, vlacher12 commented on src/components/avatar/index.tsx
> +          {`${firstName?.charAt(0)?.toUpperCase() || ''}${lastName?.charAt(0)?.toUpperCase() || ''}`}
Could you pls have a look at MUI solution? We might use smth similar to it.
https://mui.com/material-ui/react-avatar/#fallbacks

2022-04-29 12:04 UTC, vlacher12 commented on src/components/avatar/index.tsx
> +  avatarAlt?: string;
alt instead of avatarAlt

2022-05-03 10:20 UTC, vlacher12 requested changes

2022-05-03 10:20 UTC, vlacher12 commented on src/components/avatar/index.tsx
> +              {children || alt?.charAt(0) || <Icon icon={Icon.icons.profile} size={size / 2} style={{ display: 'flex' }} />}
Could you pls replace `profile` icon by `user`? If there is no `user` icon -> feel free to add
<img width="1713" alt="image" src="https://user-images.githubusercontent.com/24992556/166437397-b176c6d7-50e9-4a26-85a4-cb3a54b73a37.png">

2022-05-03 10:20 UTC, vlacher12 commented on src/components/avatar/index.tsx
> +              {children || alt?.charAt(0) || <Icon icon={Icon.icons.profile} size={size / 2} style={{ display: 'flex' }} />}
@Yhuley

2022-05-03 12:40 UTC, vlacher12 commented
@Yhuley Fix conflcits pls

2022-05-04 08:27 UTC, vlacher12 approved these changes

2022-05-04 12:53 UTC, vlacher12 commented
@sergdeev @Yhuley ok to merge

2022-05-05 17:33 UTC, merged