feat: warning, alert, success buttons added
Panenco/panenco-ui pull request #241
Opened 2022-03-30 09:47 UTC by Yhuley

2022-03-30 13:33 UTC, lazzystep commented
Could you please provide more info about it. Ideally link to trello ticket as well. Thanks in advance!

2022-04-03 13:15 UTC, GolotaMishka requested changes

2022-04-03 13:15 UTC, GolotaMishka commented on src/components/button/button-DOCS.md
> +import { PrimaryButton, SecondaryButton, Button, WarningButton, AlertButton, SucessButton, ButtonProps } from '@panenco/ui';
'Success' typo

2022-04-04 09:06 UTC, GolotaMishka approved these changes

2022-04-04 10:07 UTC, lazzystep commented
cc: @vlacher12

2022-04-06 17:03 UTC, vlacher12 commented
What problem does this PR solve? @Yhuley we can discuss in a separate meeting

2022-04-07 07:12 UTC, Yhuley commented
> we can discuss in a separate meeting

Ok, maybe today?

2022-04-15 08:05 UTC, sergdeev approved these changes

2022-04-26 09:10 UTC, closed without merging