Feat/responsive table icon prop
Panenco/panenco-ui pull request #261
Opened 2022-05-04 12:07 UTC by wigqueel

2022-05-04 12:09 UTC, vlacher12 commented
Could you pls define the purpose of this PR. What problem does it solve?

2022-05-04 12:11 UTC, wigqueel commented
> Could you pls define the purpose of this PR. What problem does it solve?

added in description

2022-05-04 15:20 UTC, vlacher12 requested changes

2022-05-05 08:00 UTC, wigqueel commented on src/components/responsive-table/columns.tsx
> +    <tr>{tableColumns}</tr>
all done

2022-05-05 08:25 UTC, vlacher12 commented
@wigqueel Create story with custom sort icons pls

2022-05-05 08:27 UTC, vlacher12 approved these changes

2022-05-05 08:57 UTC, Exiest approved these changes

2022-05-05 10:53 UTC, merged