fix: auto menuPlacement to select and new styles
Panenco/panenco-ui pull request #350
Opened 2022-10-03 14:55 UTC by Butlerskyi

Add prop to auto placement react-select menu

![image](https://user-images.githubusercontent.com/61048193/193608883-65fa13e9-3673-46db-9e42-aa262b119787.png)

2022-10-03 15:00 UTC, Butlerskyi commented
still need to fix some thing like arrow on input e.t.c, just want to know is this solution correct?

2022-10-04 10:26 UTC, vlacher12 requested changes

2022-10-04 10:26 UTC, vlacher12 commented on src/components/select/style.ts
> +      borderTopRightRadius: placementState === 'top' ? menuIsOpen && 0 : null,
extact it to separate object pls

2022-10-04 10:26 UTC, vlacher12 commented on src/components/select/style.ts
> +      borderBottomRightRadius: placementState === 'top' ? menuIsOpen && 0 : null,
same here

2022-10-04 10:26 UTC, vlacher12 commented on src/components/select/select-component.tsx
> +    setPlacementState(placement);
add check if state wasn't changed

2022-10-04 11:24 UTC, Butlerskyi commented
![](https://github.trello.services/images/mini-trello-icon.png) [Missing margin (1.5d)](https://trello.com/c/1PG1isix/4626-missing-margin-15d)

2022-10-05 11:10 UTC, vlacher12 approved these changes

2022-10-05 11:11 UTC, merged