Feat/radiobutton story
Panenco/panenco-ui pull request #363
Opened 2022-10-13 09:59 UTC by sergdeev

2023-01-17 10:59 UTC, vozbrann commented on src/components/radiobutton/index.tsx
> +            checked={checked || defaultId === id}
breaking changes

2023-01-17 11:03 UTC, vozbrann commented
It looks different from a prev version 
Old:
<img width="89" alt="image" src="https://user-images.githubusercontent.com/39827437/212882738-a31b3870-3191-4702-bc4a-62c8304ff722.png">

New:
![image](https://user-images.githubusercontent.com/39827437/212882602-a9cbdf9a-5866-4e6a-9d38-2ee6a2709c1a.png)

2023-01-20 09:38 UTC, vlacher12 requested changes

2023-01-20 09:38 UTC, vlacher12 commented on src/components/radiobutton/index.tsx
> +    const { className: inputClassName, id, ...otherInputProps } = inputProps;
do we still need default id?

2023-01-20 13:35 UTC, vozbrann commented on src/components/radiobutton/index.tsx
> +    const { className: inputClassName, id, ...otherInputProps } = inputProps;
fixed

2023-01-23 10:00 UTC, vlacher12 approved these changes

2023-01-23 15:49 UTC, lazzystep approved these changes

2023-01-23 15:53 UTC, merged