Feat/single accordion component
Panenco/panenco-ui pull request #447
Opened 2023-01-19 13:40 UTC by vozbrann

2023-01-23 10:06 UTC, vlacher12 requested changes

2023-01-23 10:06 UTC, vlacher12 commented on src/components/accordion/accordionItem/index.tsx
> +  variant?: 'outlined' | 'text';
create extra type for `'outlined' | 'text' ` and reuse it in styles as well

2023-01-23 10:06 UTC, vlacher12 commented on src/components/accordion/accordionItem/index.tsx
> +        <button type='button' className='accordionHeader' onClick={handleClick} aria-expanded={isOpen || 'false'}>
https://github.com/Panenco/panenco-ui/issues/416

2023-01-25 13:37 UTC, vlacher12 commented
fix conflicts pls

2023-01-31 15:25 UTC, lazzystep approved these changes

2023-02-06 09:11 UTC, vlacher12 approved these changes

2023-02-06 10:10 UTC, merged