Fix/grid improvements
Panenco/panenco-ui pull request #46
Opened 2021-04-12 08:44 UTC by vlacher12

![image](https://user-images.githubusercontent.com/24992556/114366499-2f827800-9b84-11eb-80d1-4c31318d74ef.png)

2021-04-13 17:44 UTC, kaliahinartem requested changes

2021-04-13 17:44 UTC, kaliahinartem commented on package.json
> +  "version": "1.1.57",
1.1.0 maybe?

2021-04-14 09:42 UTC, kaliahinartem approved these changes

2021-04-14 13:08 UTC, kkurylchenko approved these changes

2021-04-21 20:36 UTC, merged