fix: readme docs
Panenco/panenco-ui pull request #534
Opened 2023-01-31 14:41 UTC by vozbrann

2023-02-06 09:10 UTC, vlacher12 requested changes

2023-02-06 09:10 UTC, vlacher12 commented on README.md
> +Support for this package will be discontinued in the near future. Consider migrating to [Material UI](https://material-ui.com/).
MUI, Chakra, Ant

2023-02-06 09:43 UTC, vlacher12 requested changes

2023-02-06 09:43 UTC, vlacher12 commented on README.md
> +# DEPRECATED!!!
`## Will be deprecated soon`
Cause it isn't deprecated already

2023-02-06 15:55 UTC, vlacher12 approved these changes

2023-02-07 09:19 UTC, lazzystep approved these changes

2023-02-07 09:20 UTC, merged