Feat/trap focus
Panenco/panenco-ui pull request #69
Opened 2021-07-23 10:10 UTC by vozbrann

2021-07-23 10:49 UTC, kaliahinartem requested changes

2021-07-23 10:49 UTC, kaliahinartem commented on src/components/trap-focus/index.tsx
> +    const firstElement = (containerRef?.current as HTMLElement | null)?.querySelectorAll(focusableElements)[0] || null; // get first element to be focused
don't cast values

pass generic type to useRef instead

2021-07-23 10:49 UTC, kaliahinartem commented on src/components/trap-focus/index.tsx
> +    const firstElement = (containerRef?.current as HTMLElement | null)?.querySelectorAll(focusableElements)[0] || null; // get first element to be focused
|| null is redundant
youo will get null anyway if there is no element

2021-07-23 10:49 UTC, kaliahinartem commented on src/components/trap-focus/index.tsx
> +    const lastElement = focusableNodes?.[focusableNodes.length - 1] || null; // get last element to be focused
|| null is redundant

2021-07-23 10:49 UTC, kaliahinartem commented on src/components/trap-focus/index.tsx
> +    if (!Array.prototype.slice.call(focusableNodes).includes(document.activeElement)) {
why not Array.from(focusableNodes)?

2021-07-23 10:49 UTC, kaliahinartem commented on src/components/trap-focus/index.tsx
> +      (firstElement as HTMLElement)?.focus(); // add focus for the first focusable element
don't cast

2021-07-23 10:49 UTC, kaliahinartem commented on src/components/trap-focus/index.tsx
> +      (firstElement as HTMLElement)?.focus(); // add focus for the first focusable element
the type should be inferred

2021-07-23 10:49 UTC, kaliahinartem commented on src/components/trap-focus/index.tsx
> +        (lastElement as HTMLElement)?.focus(); // add focus for the last focusable element
don't cast :)

2021-07-23 10:49 UTC, kaliahinartem commented on src/components/trap-focus/index.tsx
> +        (firstElement as HTMLElement)?.focus(); // add focus for the first focusable element
aaaand don't cast :)

2021-07-23 10:49 UTC, kaliahinartem commented on src/components/trap-focus/index.tsx
> +      (activeElement as HTMLElement)?.blur();
same

2021-07-23 10:49 UTC, kaliahinartem commented on src/components/trap-focus/index.tsx
> +        (activeElement as HTMLElement)?.focus();
same

2021-09-01 09:33 UTC, kaliahinartem commented
@vozbrann any updates on this PR?

2021-09-01 11:39 UTC, vozbrann commented
> @vozbrann any updates on this PR?

@kaliahinartem Review it again, please
But maybe we should use external trap focus packages

2021-10-12 14:08 UTC, KotAleksei commented on src/components/popup/style.ts
> +  padding: 16px 24px;
let's imagine if you want to customize that component, you have to change that property for each element (header, body, footer) and only once if set it to parent + check those values in figma pls(16px for mobile and 24px for desktop)

2021-10-12 14:11 UTC, KotAleksei commented on src/components/popup/style.ts
> +  padding: 16px 24px;
check distance in the design system + comment as above

2021-10-12 14:12 UTC, KotAleksei commented on src/components/popup/README.md
> +        titleId="examplePopup"
why do you need this one ?

2021-11-18 17:04 UTC, lazzystep commented on stories/popup/SmallPopup.jsx
> +          <div style={{display: 'flex', justifyContent: 'flex-end', paddingBottom: '0'}}>
I would move styles in `style` to class

2021-11-18 17:05 UTC, lazzystep commented on stories/popup/SmallPopup.jsx
> +            <SecondaryButton aria-label="Close" onClick={handlePopupHide} style={{marginRight: '16px'}}>Cancel</SecondaryButton>
I would move styles in `style` to class

2021-11-18 17:05 UTC, lazzystep commented on stories/popup/SmallPopup.jsx
> +          <div style={{marginBottom: '16px'}}>
I would move styles in `style` to class

2021-11-18 17:05 UTC, lazzystep commented on stories/popup/LargePopup.jsx
> +            <SecondaryButton aria-label="Close" onClick={handlePopupHide} style={{marginRight: '16px'}}>Cancel</SecondaryButton>
I would move styles in `style` to class

2021-11-18 17:06 UTC, lazzystep commented on stories/popup/LargePopup.jsx
> +          <div style={{marginBottom: '16px'}}>
I would move styles in `style` to class

2021-11-18 17:06 UTC, lazzystep commented on stories/popup/LargePopup.jsx
> +          <div style={{marginBottom: '16px'}}>
I would move styles in `style` to class

2021-11-18 17:07 UTC, lazzystep commented on stories/popup/DefaultPopup.jsx
> +          <div style={{ display: 'flex', justifyContent: 'flex-end', paddingBottom: '0' }}>
I would move styles in `style` to class

2021-11-18 17:07 UTC, lazzystep commented on stories/popup/DefaultPopup.jsx
> +            <SecondaryButton aria-label="Close" onClick={handlePopupHide} style={{ marginRight: '16px' }}>
I would move styles in `style` to class

2021-11-18 17:07 UTC, lazzystep commented on stories/popup/DefaultPopup.jsx
> +          <div style={{ marginBottom: '16px' }}>
I would move styles in `style` to class

2021-11-18 17:07 UTC, lazzystep commented on stories/popup/DefaultPopup.jsx
> +          <div style={{ marginBottom: '16px' }}>
I would move styles in `style` to class

2021-11-18 17:07 UTC, lazzystep commented on stories/popup/CustomSizePopup.jsx
> +          <div style={{display: 'flex', justifyContent: 'flex-end', paddingBottom: '0'}}>
I would move styles in `style` to class

2021-11-18 17:07 UTC, lazzystep commented on stories/popup/CustomSizePopup.jsx
> +            <SecondaryButton aria-label="Close" onClick={handlePopupHide} style={{marginRight: '16px'}}>Cancel</SecondaryButton>
I would move styles in `style` to class

2021-11-18 17:08 UTC, lazzystep commented on stories/popup/CustomSizePopup.jsx
> +          <div style={{marginBottom: '16px'}}>
I would move styles in `style` to class

2021-11-18 17:10 UTC, lazzystep requested changes
Will approve after some work on changes. Read comments

2021-11-22 17:46 UTC, vlacher12 approved these changes

2021-11-22 17:46 UTC, vlacher12 commented
@lazzystep

2021-11-22 17:48 UTC, lazzystep approved these changes

2021-11-22 17:50 UTC, merged